Add python kernel sample data guide.
X-lab2017/open-digger pull request #998
Opened 2022-10-12 14:48 UTC by yoyo-wu98

Since we have added the Python Kernel of the open-digger, the guide of the Sample Data Usage with Python Kernel should be added.

2022-10-14 08:53 UTC, frank-zsy commented
My concern is that right now we add kernel related docs into `sample_data` readme, but actually the sample data doc should not be mixed with kernel doc at all because they are totally different thing here.

Can we split the kernel related docs into another place and only reference in the sample data doc?

2022-10-14 10:47 UTC, zhicheng-ning commented
A confusing situation occur.
In my sight：
![b7261eada60a6f3bcfd1229750e3c92](https://user-images.githubusercontent.com/39022409/195828640-479eb5e5-78fe-4c67-bfc6-8678b581bd7b.jpg)
In other people's insight：
![67f98ef52a8ccced4386b1a4246b6fa](https://user-images.githubusercontent.com/39022409/195828681-039d21bf-f35a-4557-b907-fdfb15da20e7.png)

2022-10-14 11:24 UTC, zhicheng-ning requested changes

2022-10-16 09:57 UTC, frank-zsy commented on sample_data/README.md
> +7. If the source code under `src` folder changed, you need to stop the notebook docker using `docker stop python_notebook_name` and restart the notebook kernel using `docker run -it --name python_not
Actually `--rm` flag is used to remove the container entity after stop the container.

The thing is for Node.js kernel, after source code change, we only need to re-compile the code and restart the kernel in JupyterLab, we don't really need to restart the container to make the change take effect.

2022-10-16 10:00 UTC, zhicheng-ning commented on sample_data/README.md
> +7. If the source code under `src` folder changed, you need to stop the notebook docker using `docker stop python_notebook_name` and restart the notebook kernel using `docker run -it --name python_not
I got, many thanks!

2022-10-22 02:24 UTC, frank-zsy commented
I think we can merge this PR now and consider how to improve the docs later.

Thanks for the contribution @yoyo-wu98 

/approve

2022-10-22 02:25 UTC, merged

2022-10-26 13:26 UTC, yoyo-wu98 commented
Many thx:)